namespace SpendWiselyAPI.Domain.Entities
{
    public class Category
    {
        public Guid Id { get; private set; }           // GUID generated by domain
        public Guid? UserId { get; private set; }      // Optional: user-specific category
        public string Name { get; private set; }
        public DateTime CreatedAt { get; private set; }
        public DateTime? UpdatedAt { get; private set; }

        // Constructor for creating a new category
        public Category(string name, Guid? userId = null)
        {
            Id = Guid.NewGuid(); // Generate new GUID for the category
            Name = name ?? throw new ArgumentNullException(nameof(name));
            UserId = userId;
            CreatedAt = DateTime.UtcNow;
        }
        // Hydration constructor for reconstituting from persistence
        public Category(Guid id , string name, DateTime createdAt ,DateTime? updatedAt , Guid? userId = null )
        {
            Id = id;
            Name = name;
            UserId = userId;
            CreatedAt = createdAt;
            UpdatedAt = updatedAt;
        }


        // Method to update category name
        public void UpdateName(string name)
        {
            if (string.IsNullOrWhiteSpace(name))
                throw new ArgumentException("Name cannot be empty", nameof(name));

            Name = name;
            UpdatedAt = DateTime.UtcNow;
        }

        public void SetUpdatedAt(DateTime updatedAt)
        {
            UpdatedAt = updatedAt;

        }
    }
}
